name: Upload artifact

on: [push]

env: 
    ARTIFACT_FILE_NAME: myartifact

jobs:
  main: 
    runs-on: ubuntu-latest

    steps:
    -  uses: actions/checkout@v2

    - name: upload
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ env.ARTIFACT_FILE_NAME }}
        path: .
