name: Test pipeline

on:
    push:
        branches:
        - 'pipeline'

jobs:
    Test: 
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: hello
          run: python hello.py

    Build:
        needs: Test
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
    
            - uses: actions/upload-artifact@v2
              with: 
                name: hello
                path: .
