name: Second

on: push

jobs:
  job1: 
    name: Job1
    runs-on: ubuntu-latest
    steps:
    - name: step-one
      run: date
  job2: 
    name: Job2
    runs-on: windows-latest
    steps:
      - name: step-one
        run: Get-Date
  job3: 
    name: Job3
    runs-on: ubuntu-latest
    needs: [job1,job2]
    steps:
      - name: step-one
        run: date